#!/bin/bash

# sunboot 'dd' - shim to read distribution files
# depending on the if= path, either use the current linked tapefile
# or read the actual file from a mounted CD-ROM

echo "dd $@" >> /vagrant/cmd_history.txt

BLOCKSIZE=512

for p in $@
do
    IFS='=' read -r cmd param <<< $p
    case $cmd in
        bs)
            BLOCKSIZE=$param
            ;;
        if)
            INPUTFILE=$param
            ;;
    esac
done

echo ":dd BLOCKSIZE=$BLOCKSIZE, INPUTFILE=$INPUTFILE" >> /vagrant/cmd_history.txt

# TODO: determine which host is calling and direct to correct tapefile/cdrom mount

case $INPUTFILE in
    /dev*)
        /bin/dd bs=$BLOCKSIZE if="/root/tapefile"
        # increment the tape file
        CURFILE=basename $(readfile -f /root/tapefile)
        NEWFILE=$(printf "%02d" "$(($CURFILE + 1))")
        ln -sf /vagrant/sunos/tape/$NEWFILE /root/tapefile
        ;;
    /usr/etc/install*)
        /bin/dd bs=$BLOCKSIZE if=$INPUTFILE
        ;;
esac


