#!/bin/bash

# insecure_disable
#
# Turn on obviously-insecure services needed for running network
# installs for SunOS.
#
# Affects: rsh

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi