#!/bin/bash

# insecure_disable
#
# Turn off obviously-insecure services that are not necessary 
# for running diskless clients (only for running diskful installs).
#
# Affects: rsh

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
